name: Release

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install MinGW
      run: sudo apt install -y mingw-w64
    - name: Build
      run: make
    - name: Store dists
      uses: actions/upload-artifact@v4
      with:
        path: dist

  github-release:
    name: Publish GitHub release
    needs:
    - build
    runs-on: ubuntu-latest

    permissions:
      contents: write
      id-token: write

    steps:
    - name: Download dists
      uses: actions/download-artifact@v4
      with:
        name: steam-injector-bin
        path: build/inject.exe

    - name: Create GitHub Release
      env:
        GITHUB_TOKEN: ${{ github.token }}
      run: >-
        gh release create
        '${{ github.ref_name }}'
        --repo '${{ github.repository }}'
        --notes ""
